# @@@DLT_SNIPPET_START example
[destination.qdrant.credentials]
location = ""
api_key = ""

[sources.zendesk.zendesk_support.credentials]
password = ""
subdomain = ""
email = ""
# @@@DLT_SNIPPET_END example
